<?php

return [
    'include' => 'Common',
    'modules/aggiornamenti' => 'Modules\Aggiornamenti',
    'modules/anagrafiche' => 'Modules\Anagrafiche',
    'modules/backups' => 'Modules\Backups',
    'modules/emails' => 'Modules\Emails',
    'modules/articoli' => 'Modules\Articoli',
    'modules/checklists' => 'Modules\Checklists',
    'modules/ritenute' => 'Modules\Ritenute',
    'modules/ritenute_contributi' => 'Modules\RitenuteContributi',
    'modules/rivalse' => 'Modules\Rivalse',
    'modules/newsletter' => 'Modules\Newsletter',
    'modules/iva' => 'Modules\Iva',
    'modules/ddt' => 'Modules\DDT',
    'modules/fatture' => 'Modules\Fatture',
    'modules/ordini' => 'Modules\Ordini',
    'modules/preventivi' => 'Modules\Preventivi',
    'modules/contratti' => 'Modules\Contratti',
    'modules/interventi' => 'Modules\Interventi',
    'modules/pagamenti' => 'Modules\Pagamenti',
    'modules/statistiche' => 'Modules\Statistiche',
    'modules/scadenzario' => 'Modules\Scadenzario',
    'modules/primanota' => 'Modules\PrimaNota',
    'modules/utenti' => 'Modules\Utenti',
    'modules/stato_servizi' => 'Modules\StatoServizi',
    'modules/stati_intervento' => 'Modules\StatiIntervento',
    'modules/stati_preventivo' => 'Modules\StatiPreventivo',
    'modules/stati_contratto' => 'Modules\StatiContratto',
    'modules/tipi_intervento' => 'Modules\TipiIntervento',
    'modules/categorie_documenti' => 'Modules\CategorieDocumentali',
    'modules/listini' => 'Modules\Listini',
    'modules/impianti' => 'Modules\Impianti',
    'modules/impostazioni' => 'Modules\Impostazioni',
    'plugins/exportFE' => 'Plugins\ExportFE',
    'plugins/importFE' => 'Plugins\ImportFE',
    'plugins/receiptFE' => 'Plugins\ReceiptFE',
    'plugins/dichiarazioni_intento' => 'Plugins\DichiarazioniIntento',
    'plugins/pianificazione_interventi' => 'Plugins\PianificazioneInterventi',
    'plugins/pianificazione_fatturazione' => 'Plugins\PianificazioneFatturazione',
    'plugins/statistiche_articoli' => 'Plugins\StatisticheArticoli',
    'plugins/fornitori_articolo' => 'Plugins\FornitoriArticolo',
];
